package jone.helper.greendao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import jone.helper.bean.Notebook;

import jone.helper.greendao.dao.NotebookDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig notebookDaoConfig;

    private final NotebookDao notebookDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        notebookDaoConfig = daoConfigMap.get(NotebookDao.class).clone();
        notebookDaoConfig.initIdentityScope(type);

        notebookDao = new NotebookDao(notebookDaoConfig, this);

        registerDao(Notebook.class, notebookDao);
    }
    
    public void clear() {
        notebookDaoConfig.getIdentityScope().clear();
    }

    public NotebookDao getNotebookDao() {
        return notebookDao;
    }

}
